# Generated by Django 4.2.5 on 2023-09-27 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_alter_post_title_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='recipe',
        ),
    ]
