# Generated by Django 4.2.5 on 2023-10-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0016_alter_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsletterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsEmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
