# Generated by Django 4.2.5 on 2023-10-08 21:17

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0017_newslettermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ct_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='category_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='category', unique=True),
        ),
    ]
