# Generated by Django 4.2.5 on 2023-10-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0018_category_ct_slug_post_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
