# Generated by Django 4.2.5 on 2023-10-12 20:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0022_alter_post_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='recipe',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Recipe'),
        ),
    ]
