# Generated by Django 4.2.5 on 2023-10-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0023_alter_post_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click link above to read blog posts', max_length=255),
        ),
    ]
