# Generated by Django 4.2.5 on 2023-10-30 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0031_contact_alter_newslettermodel_newsemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header_image',
            new_name='image',
        ),
    ]
