# Generated by Django 4.2.5 on 2023-11-04 21:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0033_alter_comment_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snippet',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Recipe'),
        ),
    ]
