# Generated by Django 4.2.5 on 2023-11-04 21:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0034_remove_post_snippet_remove_post_title_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ingredients'),
        ),
    ]
